#Project Language
language: php

#Versions to test against
php:
  - '7.0'
  - '7.1'
  - hhvm

before_install:
  #- echo "extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./vendor/bin/test-reporter